i hate myself and want to die

diff --git a/.local/bin/lapce b/.local/bin/lapce
--- a/.local/bin/lapce
+++ b/.local/bin/lapce
@@ -1,5 +1,7 @@
 #!/bin/sh
 #
+# Launches lapce (flatpak version) text editor.
+#
 # Copyright 2026 Kinderfeld
 #
 # Redistribution and use in source and binary forms, with or without
@@ -25,5 +27,11 @@
 # POSSIBILITY OF SUCH DAMAGE.
 #
 
-flatpak run dev.lapce.lapce
+if flatpak run dev.lapce.lapce
+then
+    exit 0
+else
+    printf "can't launch lapce; is it installed (flatpak)?\n" >&2
+    exit 1
+fi
 
diff --git a/.local/bin/librewolf b/.local/bin/librewolf
--- a/.local/bin/librewolf
+++ b/.local/bin/librewolf
@@ -2,6 +2,8 @@
 #
 # Copyright 2026 Kinderfeld
 #
+# Launches librewolf (flatpak version) web browser.
+#
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
 #
@@ -25,4 +27,10 @@
 # POSSIBILITY OF SUCH DAMAGE.
 #
 
-flatpak run io.gitlab.librewolf-community &
+if flatpak run io.gitlab.librewolf-community
+then
+    exit 0
+else
+    printf "can't launch librewolf. is it installed (flatpak)?\n" >&2
+    exit 1
+fi
diff --git a/bin/fix-wifi b/bin/fix-wifi
--- a/bin/fix-wifi
+++ b/bin/fix-wifi
@@ -1,6 +1,4 @@
-#!/bin/sh
-#
-# Launces libreoffice (flatpak version) office suite.
+#!/bin/bash
 #
 # Copyright 2026 Kinderfeld
 #
@@ -27,11 +25,50 @@
 # POSSIBILITY OF SUCH DAMAGE.
 #
 
-if flatpak run org.libreoffice.LibreOffice
+if ! morpheus --check-privileges
 then
-    exit 0
-else
-    printf "can't launch libreoffice. is it installed (flatpak)?\n" >&2
+    printf "[!] root required.\n" >&2
     exit 1
 fi
+
+# pids=$(
+#    ps -o pid,ppid,user,args -C wpa_supplicant |
+#    awk 'NR > 1 { print $1 }'
+# )
+
+# if [ -z "${pids}" ]
+# then
+#    printf "[*] no 'wpa_supplicant' processes found.\n"
+#    # exit 0
+# fi
+
+# printf "[...] killing wpa_supplicant PIDs:"
+# printf "%s" "${pids}" 
+# kill "${pids}" && printf "[*] done.\n"
+# sleep 2
+
+# remaining=$(
+#    ps -o pid= -C wpa_supplicant |
+#    awk '{ print $1 }'
+# )
+
+# if [ -n "${remaining}" ]
+# then
+#    printf "[...] force-killing remaining PIDs: "
+#    printf "%s" "${remaining}"
+#    kill -KILL "${remaining}"
+#    printf "[*] probably done.\n"
+# fi
+
+printf "[...] flushing ip routes...\n" && \
+    ip addr flush dev wlan0 && ip route flush dev wlan0 && printf "[*] done.\n"
+
+printf "[...] restarting 'connman' service...\n" && \
+    rc-service connman restart && printf "[*] done.\n"
+
+printf "now you can run these at 'connmanctl':\n"
+printf "    enable wifi\n"
+printf "    scan wifi\n"
+printf "    agent on\n"
+printf "    connect <identifier>\n"
 
diff --git a/bin/setup-basic-ufw b/bin/setup-basic-ufw
--- a/bin/setup-basic-ufw
+++ b/bin/setup-basic-ufw
@@ -1,7 +1,5 @@
 #!/bin/sh
 #
-# Launces libreoffice (flatpak version) office suite.
-#
 # Copyright 2026 Kinderfeld
 #
 # Redistribution and use in source and binary forms, with or without
@@ -27,11 +25,80 @@
 # POSSIBILITY OF SUCH DAMAGE.
 #
 
-if flatpak run org.libreoffice.LibreOffice
-then
-    exit 0
-else
-    printf "can't launch libreoffice. is it installed (flatpak)?\n" >&2
-    exit 1
-fi
+log()
+{
+    printf "[info] %s...\n" "$1"
+}
+
+install_ufw()
+{
+    log "installing ufw"
+
+    if morpheus -PM install ufw
+    then
+        log "ufw installed successfully"
+        return 0
+    else
+        log "failed to install ufw"
+        return 1
+    fi
+}
+
+setup_rules_ufw()
+{
+    log "configuring ufw defaults"
+
+    log "deny incoming and allow outgoing..."
+    ufw default deny incoming
+    ufw default allow outgoing
+
+    log "set 'medium' log level"
+    ufw logging medium
+
+    log "deny FTP"
+    ufw deny in 21/tcp
+    ufw deny in 21/udp
+
+    log "deny SSH"
+    ufw deny in 22/tcp
+    ufw deny in 22/udp
+    ufw deny in 2222/tcp
+    ufw deny in 2222/udp
+
+    log "deny TELNET"
+    ufw deny in 23/tcp
+    ufw deny in 23/udp
+
+    if ufw --force enable
+    then
+        log "ufw enabled successfully"
+        return 0
+    else
+        log "failed to enable ufw"
+        return 1
+    fi
+}
+
+main()
+{
+    log "'setup-basic-ufw.sh' started"
+
+    if ! morpheus --check-privileges
+    then 
+        log "root privileges not present. exiting"
+        exit 1
+    fi
+
+    if install_ufw && setup_rules_ufw
+    then
+        log "'setup-basic-ufw.sh' completed successfully"
+        ufw status numbered
+        exit 0
+    else
+        log "'setup-basic-ufw.sh' failed"
+        exit 1
+    fi
+}
+
+main
 
